### ISSUE TITLE
How can anyone steal RAM

### ISSUE THREAD

**Issue by dennistocker** [EOSEssentials/EOS-Proxy-Token#2]
Sorry that this is not an issue. I just want to known what this contract is used for. 
The README said that "A malicious user can install code on their account which will allow them to insert rows in the name of another account sending them tokens", but how can anyone do that without the sender's permission? Would you kindly show me an example?

**Comment by dennistocker** [comment]
okay, i've found one.
https://mp.weixin.qq.com/s/OE7hxaXyrQ6Ssn-2c55GBA

**Comment by nsjames** [comment]
Right. Inline transfers carry along with them the database permissions of their sender, which allows the recipient to insert rows in their name.
